### ISSUE TITLE
Memory corruption in SBCL 1.3.18

### ISSUE THREAD

**Issue by syll-dev** [cl-plus-ssl/cl-plus-ssl#48] opened 2017-06-15 21:20 UTC
I have an SBCL error due to memory corruption when calling
`(cl+ssl:make-ssl-client-stream (usocket:socket-stream (usocket:socket-connect "google.com" 443 :element-type 'flexi-streams:octet)))`

This does work with SBCL 1.3.17 but not with SBCL 1.3.18 (here, but the problem does not seem the same for everyone).

Details on the bug on [SBCL tracker](https://bugs.launchpad.net/sbcl/+bug/1697528)

I have tried cl+ssl last version on master (placed on quicklisp's local-projects) but I get the "same" error. Unfortunately I can't get a very useful backtrace from SBCL (but another contributor did get a better one, see SBCL bug tracker ; his/her backtrace has (probably) been gotten with quicklisp's version of cl+ssl).

I use openssl, not libressl.

Maybe related to these (close) bugs : #41 #42

**Comment by stassats** [comment] 2017-06-24 12:40
Not caused by cl+ssl, you can close it.

**Comment by avodonosov** [comment] 2017-06-25 08:05
@stassats, thanks for the info

**Closed by avodonosov** 2017-06-25 08:05 UTC
