### ISSUE TITLE
Use of CL+SSL by Drakma web client results in error

### ISSUE THREAD

**Issue by ctlaux** [cl-plus-ssl/cl-plus-ssl#10] opened 2015-01-13 17:07 UTC
Drakma web client using CL+SSL results in this error:

(drakma:http-request "https://health.edcast.org/learn/first-responder-trauma-emergency-care-program-fall-2014")

A failure in the SSL library occurred on handle #.(SB-SYS:INT-SAP #X7FFFEC01E560) (return code: 1). SSL error queue:
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[Condition of type CL+SSL::SSL-ERROR-SSL]

Can anyone tell me how to fix or work around this?

**Comment by avodonosov** [comment] 2015-01-13 19:49
Have you tried to google for that SSL error?

**Comment by avodonosov** [comment] 2015-01-13 19:49
I mean the error number, 14077410

**Comment by ctlaux** [comment] 2015-01-15 20:33
Googling didn't yield anything that helps

**Comment by avodonosov** [comment] 2015-01-15 20:36
Unfortunately I don't have an answer. But briefly looking at results of

 https://www.google.by/search?q=14077410+SSL23_GET_SERVER_HELLO+alert+handshake+failure

seems like there might be useful information.

**Comment by martinflack** [comment] 2015-05-05 00:14
I believe the issue is that the example domain requires SNI in order to satisfy its connection requirements (http://en.wikipedia.org/wiki/Server_Name_Indication) and CL+SSL is not asking for the SNI extension to be activated.

As of today this fails:
`openssl s_client -connect health.edcast.org:443`
...but this works:
`openssl s_client -connect health.edcast.org:443 -servername health.edcast.org`

I noticed the same connection error with www.coursera.org today via DRAKMA.

I did some work within CL-HTTP2-PROTOCOL to support SNI with CL+SSL but I did not yet upstream anything as it's still a work-in-progress. You can take a look at https://github.com/akamai/cl-http2-protocol/blob/master/tcp-ssl.lisp for the general idea.

If you can hand an SSL context to CL+SSL through DRAKMA it might be possible to setup outside of the HTTP-REQUEST call?

**Comment by avodonosov** [comment] 2015-05-05 10:18
@martinflack There is another request to add SNI to CL+SSL https://github.com/cl-plus-ssl/cl-plus-ssl/pull/7

I didn't commit because I don't understand the code. Can you have a look and comment on the questions I asked there?

**Comment by avodonosov** [comment] 2015-05-15 05:31
So, as #7 is closed, it's possible to specify server name. We now need somebody to fix adjust drakma.

**Comment by CodyReichert** [comment] 2015-07-28 17:43
For anyone else coming across this -  it seems that the master branch of Drakma takes care of this (edicl/drakma#66).

I cloned Drakma into quicklisp/local-projects, and was able to successfully make the request mentioned above, as well as a few others I got the same error on.

**Comment by avodonosov** [comment] 2015-07-28 18:27
@CodyReichert thanks for the notice. So we can close this issue.

**Closed by avodonosov** 2015-07-28 18:27 UTC
